services:
  whatsapp-selenium:
    build: .
    volumes:
      - ./screenshots:/app/screenshots  # Monta el directorio de capturas de pantalla
      - ./scripts:/app/scripts          # Volumen para los scripts Python
      - ./data/firefox:/app/firefox_profile         # Volumen para los scripts Python
    environment:
      - DISPLAY=:99
      - TZ:"America/Santo_Domingo"
    shm_size: '2gb'
    networks:
      - default
    ports:
      - "4442-4444:4442-4444"
    container_name: whatsapp-selenium
    working_dir: /app/scripts
    #command: /bin/bash -c "pip install selenium && python test_google_search.py"

networks:
  default:
    name: grid
